# Archivo de configuración para el perfil de Producción (AWS)
# Aquí solo definimos los VALORES que queremos inyectar en las variables ${} del application.yml base.

ALLOWED_ORIGINS: "http://localhost:4200" # Cambia esto por la URL real de tu front de producción cuando la tengas (ej: .com)
USERS_SERVICE_URI: "http://3.151.143.108:8081"
SPECIALIST_SERVICE_URI: "http://3.151.143.108:8082"
DIARY_SERVICE_URI: "http://3.151.143.108:8083"
NOTIFICATIONS_SERVICE_URI: "http://3.151.143.108:8085"
EUPHORIA_SERVICE_URI: "http://20.85.243.149:8000"

# También puedes cambiar el secreto en producción por uno más seguro
JWT_SECRET: "MiClaveSecretaSuperSeguraParaJWTDebeSerMuyLarga123456789"
