server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # ── Usuarios (Spring Boot) ──
        - id: users-service
          uri: http://ec2-3-148-176-128.us-east-2.compute.amazonaws.com:8081
          predicates:
            - Path=/api/auth/**, /api/personas/**, /api/documents/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        # ── Specialist (NestJS) ──
        - id: specialist-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/specialist/**, /api/appointment/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        # ── Euphoria (Python) ──
        - id: euphoria-service
          uri:  https://euphoria-app.politedune-01b83c33.westus2.azurecontainerapps.io
          predicates:
            - Path=/api/euphoria/**
          filters:
            - RewritePath=/api/euphoria/(?<segment>.*), /$\{segment}

        # ── Diario (Spring Boot) ──
        - id: diary-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/diary/**, /api/habits/**, /api/album/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

          # ── Notificaciones (Spring Boot) ──
        - id: notifications-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/notificaciones/**, /api/tokens/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

jwt:
  secret: MiClaveSecretaSuperSeguraParaJWTDebeSerMuyLarga123456789

gateway:
  open-endpoints:
    - /api/auth/login
    - /api/auth/register
    - /api/auth/register-therapist
    - /api/auth/google
    - /api/auth/forgot-password
