# Archivo de configuración para el perfil de Producción (AWS)
# Aquí solo definimos los VALORES que queremos inyectar en las variables ${} del application.yml base.

ALLOWED_ORIGINS: "https://sanity-chi-eight.vercel.app" # Cambia esto por la URL real de tu front de producción cuando la tengas (ej: .com)
USERS_SERVICE_URI: "http://3.151.143.108:8081"
SPECIALIST_SERVICE_URI: "http://18.118.129.115:8082"
DIARY_SERVICE_URI: "http://18.224.82.188:8083"
NOTIFICATIONS_SERVICE_URI: "http://18.224.82.188:8085"
EUPHORIA_SERVICE_URI: "https://new-euphoria-production.up.railway.app"

# También puedes cambiar el secreto en producción por uno más seguro
JWT_SECRET: "MiClaveSecretaSuperSeguraParaJWTDebeSerMuyLarga123456789"
